# Generated by Django 4.1.3 on 2023-05-11 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='fecha_reg',
            field=models.DateField(null=True),
        ),
    ]
