# Generated by Django 4.1.3 on 2023-05-11 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_participante_fecha_reg'),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='codigo',
            field=models.CharField(db_column='codigo', max_length=8, null=True, unique=True),
        ),
    ]
